name: Rust

on:
  push:
    branches: [ "main", "staging", "dev" ]
  pull_request:
    branches: [ "main", "staging", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      working-directory: server
    - name: Run tests
      run: cargo test --verbose
      working-directory: server
